<?php

namespace TeamBundle\Repository;

/**
 * roleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roleRepository extends \Doctrine\ORM\EntityRepository
{
}
