<?php

namespace TeamBundle\Repository;

/**
 * teamm_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class teamm_userRepository extends \Doctrine\ORM\EntityRepository
{
}
