<?php

namespace TeamBundle\Repository;

/**
 * team_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class team_userRepository extends \Doctrine\ORM\EntityRepository
{
}
