<?php

namespace TeamBundle\Repository;

/**
 * teamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class teamRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM AppBundle:Post p
                WHERE p.title LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function getMyTeams($user)
    {

        $qb = $this->createQueryBuilder('p');
        $qb

            ->join('TeamBundle:team_user','t' )
            ->andWhere('t.userId = :user' )
            ->andWhere('p.id = t.teamId')
            ->andWhere('p.ind = 0')
            ->setParameter('user', $user);
        // var_dump($qb->getQuery()->getResult());
        return $result = $qb->getQuery()->getResult();

    }
}
