<?php

namespace TeamBundle\Repository;

/**
 * teamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class teamRepository extends \Doctrine\ORM\EntityRepository
{
}
