<?php

namespace FeatureBundle\Repository;

/**
 * featureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class featureRepository extends \Doctrine\ORM\EntityRepository
{
}
