messaging_homepage:
    path:     /message/{id}
    defaults: { _controller: MessagingBundle:Default:index }
create_thread:
    path:   /create_thread/{id}
    defaults:   {_controller: MessagingBundle:Default:createThread}
inbox:
    path:   /inbox
    defaults:   {_controller: MessagingBundle:Default:inbox}

reply:
    path: /reply
    defaults:   {_controller: MessagingBundle:Default:reply}
    methods: [post]
refresh:
    path: /refresh
    defaults:   {_controller: MessagingBundle:Default:refresh}
    methods: [post]
SendRequest:
    path: /Send_request
    defaults:   {_controller: MessagingBundle:FriendShip:SendRequest}
    methods: [post]
DisplayUsers:
    path: /display_users
    defaults:   {_controller: MessagingBundle:FriendShip:DisplayUsers}
AddFriend:
    path: /add_friend/{id}
    defaults:   {_controller: MessagingBundle:FriendShip:AddFriend}