security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Firewall pour la page de connexion, et récupération du mot de passe

        main:
            pattern: ^/
            form_login:
                success_handler: authentication.handler.login_success_handler
                remember_me: true
                csrf_token_generator: security.csrf.token_manager
                default_target_path: 'dashboard'

            logout:       true
            anonymous:    true
            logout_on_user_change: true



    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dash/, role: ROLE_ADMIN }
        - { path: ^/app/, role: ROLE_USER }
        - { path: ^/forum/, role: ROLE_USER }
        - { path: ^/chat/, role: ROLE_USER }


