sprint_index:
    path:     /sprint
    defaults: { _controller: "SprintBundle:Sprint:index" }
    methods:  GET

sprint_show:
    path:     /{id}/show
    defaults: { _controller: "SprintBundle:Sprint:show" }
    methods:  GET

sprint_new:
    path:     /new
    defaults: { _controller: "SprintBundle:Sprint:new" }
    methods:  [GET, POST]

sprint_edit:
    path:     /{id}/edit
    defaults: { _controller: "SprintBundle:Sprint:edit" }
    methods:  [GET, POST]

sprint_delete:
    path:     /{id}/delete
    defaults: { _controller: "SprintBundle:Sprint:delete" }
    methods:  DELETE
