services:
    activity.ajouter:
        class: ActivityBundle\Controller\ActivityController
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Borsaco\TelegramBotApiBundle\Service\Bot:
        arguments: ['@service_container']
