<?php

namespace UserstoryBundle\Repository;

/**
 * featureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class featureRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){

        return $this->$this->getEntityManager()->CreateQuery(
            'SELECT p FROM UserstoryBundle:feature p WHERE p.name LIKE :str'

        )
            ->setParameter('str','%',$str,'$')
            ->getResult();
    }
}
