<?php

namespace UserstoryBundle\Repository;

/**
 * featurecommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class featurecommentRepository extends \Doctrine\ORM\EntityRepository
{
}
