<?php

namespace UserstoryBundle\Repository;

/**
 * userstoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userstoryRepository extends \Doctrine\ORM\EntityRepository
{
}
