<?php

namespace UserstoryBundle\Repository;

/**
 * userstorycommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userstorycommentRepository extends \Doctrine\ORM\EntityRepository
{
}
