Sprint_homepage:
    path:     /sprint/{id}
    defaults: { _controller: SprintBundle:Default:AddS }
archiverSprint:
    path:     /archiver/{id}
    defaults: { _controller: SprintBundle:Default:archiverS }
addSprint:
    path:   /AddSprint
    defaults: { _controller: SprintBundle:Default:AddS }
