team_homepage:
    path:     /role
    defaults: { _controller: TeamBundle:Default:index }



ajout_team:
    path:     /ajtteam
    defaults: { _controller: TeamBundle:Team:AddP }

affiche_team:
    path:     /affteam
    defaults: { _controller: TeamBundle:Team:aff }

edit_team:
    path:     /editteam/{id}
    defaults: { _controller: TeamBundle:Team:edit }

archive_team:
    path:     /archteam/{id}
    defaults: { _controller: TeamBundle:Team:archive}