team_homepage:
    path:     /role
    defaults: { _controller: TeamBundle:Default:index }

ajout_team:
    path:     /ajtteam
    defaults: { _controller: TeamBundle:Team:AddP }

affiche_team:
    path:     /affteam
    defaults: { _controller: TeamBundle:Team:aff }
affiche_members:
    path:     /teammembers/{id}
    defaults: { _controller: TeamBundle:Team:afficherT }
edit_team:
    path:     /editteam/{id}
    defaults: { _controller: TeamBundle:Team:edit }

archive_team:
    path:     /archteam/{id}
    defaults: { _controller: TeamBundle:Team:archive}

archive_team1:
    path:     /archt/{id}
    defaults: { _controller: TeamBundle:Team:archiveB}

desarchive_team1:
    path:     /desar/{id}
    defaults: { _controller: TeamBundle:Team:desar}

show_team_back:
    path:   /backteam
    defaults: { _controller: TeamBundle:Team:showback }

affecter:
    path:   /afcteam/{id}
    defaults: { _controller: TeamBundle:Default:affecter }
envoyer_mail:
    path:   /afcteam/{id}
    defaults: { _controller: TeamBundle:Default:mail }

pdfexample:
    path:     /pdf-example
    defaults: { _controller: TeamBundle:Pdf:index }

affiche_team1:
    path:     /affteamB
    defaults: { _controller: TeamBundle:Team:affB }

affecterUser:
    path:   /affuser/{team_id}/{user_id}
    defaults: { _controller: TeamBundle:Default:affecterUser }

search_ajax:
    path:     /search
    defaults: { _controller: TeamBundle:Team:search }