team_homepage:
    path:     /role
    defaults: { _controller: TeamBundle:Default:index }



ajout_team:
    path:     /ajtteam
    defaults: { _controller: TeamBundle:Team:AddP }

affiche_team:
    path:     /affteam
    defaults: { _controller: TeamBundle:Team:aff }

edit_team:
    path:     /editteam/{id}
    defaults: { _controller: TeamBundle:Team:edit }

archive_team:
    path:     /archteam/{id}
    defaults: { _controller: TeamBundle:Team:archive}

archive_team1:
    path:     /archt/{id}
    defaults: { _controller: TeamBundle:Team:archiveB}

desarchive_team1:
    path:     /desar/{id}
    defaults: { _controller: TeamBundle:Team:desar}

show_team_back:
    path:   /backteam
    defaults: { _controller: TeamBundle:Team:showback }

affecter:
    path:   /afcteam/{id}
    defaults: { _controller: TeamBundle:Default:affecter }

pdfexample:
    path:     /pdf-example
    defaults: { _controller: TeamBundle:Pdf:index }

affiche_team1:
    path:     /affteam1
    defaults: { _controller: TeamBundle:Team:affB }


