<?php

namespace ProjectBundle\Repository;

/**
 * projectScrumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projectScrumRepository extends \Doctrine\ORM\EntityRepository
{
}
