homepage:
  path:     /
  defaults: { _controller: MainBundle:Default:index }
homepageback:
  path:     /dashboard
  defaults: { _controller: MainBundle:Default:dashboard }
dashboard:
  path:     /Dash
  defaults: { _controller: MainBundle:Default:dash}
recaptcha:
  path:     /captcha
  defaults: { _controller: MainBundle:Default:recaptcha}
captchaverify:
  path:     /captchaverif
  defaults: { _controller: MainBundle:Default:captchaverify}

