homepage:
  path:     /
<<<<<<< HEAD
  defaults: { _controller: MainBundle:Default:index }
=======
  defaults: { _controller: MainBundle:Default:contact }
>>>>>>> parent of cf3e3f7... contact us part 2
