services:
#    main.example:
#        class: MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    main.registration_listener:
      class: MainBundle\EventListener\RegistrationListener
      arguments: []
      tags:
        - { name: kernel.event_subscriber }