<?php

namespace MessagingBundle\Repository;

/**
 * FriendShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendShipRepository extends \Doctrine\ORM\EntityRepository
{
}
