<?php

namespace MessagingBundle\Repository;

/**
 * MessageMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageMetadataRepository extends \Doctrine\ORM\EntityRepository
{
}
