<?php

namespace MessagingBundle\Repository;

/**
 * ThreadMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadMetadataRepository extends \Doctrine\ORM\EntityRepository
{
}
