<?php

namespace ForumBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function countForUser($user){
        return $this->createQueryBuilder('q')
            ->SELECT('COUNT(q.id)')
            ->where('q.User = :user')
            ->setParameter('user' , $user)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
