<?php

namespace ForumBundle\Repository;

use ForumBundle\Entity\Badge;
use Doctrine\ORM\Query\Expr;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param int $user_id
     * @param string $action
     * @param int $action_count
     * @return Badge
     */
    public function findWithUnlockForAction(int $user_id, string $action, int $action_count): Badge {
        return $this->createQueryBuilder('b')
            ->where('b.actionName = :action_name')
            ->andWhere('b.actionCount = :action_count')
            ->andWhere('u.user = :user_id OR u.user IS NULL')
            ->leftJoin('b.unlocks', 'u', Expr\Join::WITH, 'u.user = :user_id')
            ->select('b, u')
            ->setParameters([
                'action_count'  => $action_count,
                'action_name'   => $action,
                'user_id'       => $user_id
            ])
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * Find all badges unlocked by a specific user
     *
     * @param int $user_id
     * @return Badge[]
     */
    public function findUnlockedFor(int $user_id): array {
        return $this->createQueryBuilder('b')
            ->join('b.unlocks', 'u')
            ->where('u.user = :user_id')
            ->setParameter('user_id', $user_id)
            ->getQuery()
            ->getResult();
    }

}
