<?php

namespace ForumBundle\Repository;

/**
 * BadgeUnlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeUnlockRepository extends \Doctrine\ORM\EntityRepository
{
}
