<?php
namespace ForumBundle\Repository;
/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{public function getOtherQuestions($user)
{
    $qb = $this->createQueryBuilder('u');
    $qb->where('u.User != :user')
        ->setParameter('user', $user);

    return $qb->getQuery()
        ->getResult();
}
}
