<?php

namespace TasksBundle\Repository;

/**
 * taskuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class taskuserRepository extends \Doctrine\ORM\EntityRepository
{
}
