<?php

namespace TasksBundle\Repository;

/**
 * task_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class task_userRepository extends \Doctrine\ORM\EntityRepository
{
}
