project_homepage:
    path:   /Project
    defaults: { _controller: ProjectBundle:Default:indexP }
showProject:
    path:   /Show
    defaults: { _controller: ProjectBundle:Default:ShowP }

createProject:
    path:   /Show
    defaults: { _controller: ProjectBundle:Default:ShowP }
