project_homepage:
    path:   /Project
    defaults: { _controller: ProjectBundle:Default:indexP }

showProject:
    path:   /Show
    defaults: { _controller: ProjectBundle:Default:ShowP }

addProject:
    path:   /Add
    defaults: { _controller: ProjectBundle:Default:AddP }
archiverProject:
    path:     /archiver/{id}
    defaults: { _controller: ProjectBundle:Default:archiverP }