<?php

namespace ActivityBundle\Repository;

/**
 * MeetingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingsRepository extends \Doctrine\ORM\EntityRepository
{
}
